# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Python\Pile\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow,QDialog
import Ui_GetAlpha


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("selection-background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(570, 20, 201, 181))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/png/image/p1.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 281, 18))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_2.setToolTipDuration(0)
        self.radioButton_2.setAutoFillBackground(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radioButton_2)
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup_2.addButton(self.radioButton_3)
        self.horizontalLayout.addWidget(self.radioButton_3)
        self.radioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup_2.addButton(self.radioButton)
        self.horizontalLayout.addWidget(self.radioButton)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 70, 452, 51))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.ei = QtWidgets.QLabel(self.widget)
        self.ei.setObjectName("ei")
        self.gridLayout.addWidget(self.ei, 0, 0, 1, 1)
        self.eiedit = QtWidgets.QLineEdit(self.widget)
        self.eiedit.setObjectName("eiedit")
        self.gridLayout.addWidget(self.eiedit, 0, 1, 1, 1)
        self.alpha = QtWidgets.QLabel(self.widget)
        self.alpha.setObjectName("alpha")
        self.gridLayout.addWidget(self.alpha, 1, 0, 1, 1)
        self.alphaedit = QtWidgets.QLineEdit(self.widget)
        self.alphaedit.setObjectName("alphaedit")
        self.gridLayout.addWidget(self.alphaedit, 1, 1, 1, 1)
        self.calapha = QtWidgets.QPushButton(self.widget)
        self.calapha.setObjectName("calapha")
        self.gridLayout.addWidget(self.calapha, 1, 2, 1, 1)
        self.calapha_2 = QtWidgets.QPushButton(self.widget)
        self.calapha_2.setObjectName("calapha_2")
        self.gridLayout.addWidget(self.calapha_2, 1, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        self.child = QDialog()
        self.child_ui = Ui_GetAlpha.Ui_Dialog()
        self.child_ui.setupUi(self.child)
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        self.buttonGroup_2.buttonClicked['int'].connect(self.label.clear)
        self.calapha.clicked.connect(self.openAlpha)
        self.calapha_2.clicked.connect(self.PutCalValueToFrom)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButton_2.setText(_translate("MainWindow", "pic1"))
        self.radioButton_3.setText(_translate("MainWindow", "pic2"))
        self.radioButton.setText(_translate("MainWindow", "pic3"))
        self.ei.setText(_translate("MainWindow", "EI（桩刚度）"))
        self.alpha.setText(_translate("MainWindow", "α（水平位移系数）"))
        self.calapha.setText(_translate("MainWindow", "计算"))
        self.calapha_2.setText(_translate("MainWindow", "将计算值填入输入框"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))

    def openAlpha(self):
        self.child.show()
    
    def PutCalValueToFrom(self):
        if hasattr(self.child_ui,'alpha'):
            self.alphaedit.setText("%s"%(self.child_ui.alpha))
            self.eiedit.setText("%s"%(self.child_ui.EI))
        else:
            pass
import png_rc
