# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\HotPile\UI\Ui_ProductMgr\Ui_ProductMgr.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget,QDialog
from Tools import ProductSelect
import os
import xlrd


class Ui_ProductMgr(QWidget):
    def __init__(self, parent = None):
        super(QWidget, self).__init__(parent)
        self.setupUi()
        self.LoadData()

    def setupUi(self):
        self.setObjectName("Form")
        self.resize(1800, 1000)
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(890, 20, 191, 31))
        self.label.setStyleSheet("font: 75 16pt \"Agency FB\";")
        self.label.setObjectName("label")
        self.importFileData = QtWidgets.QPushButton(self)
        self.importFileData.setGeometry(QtCore.QRect(20, 60, 75, 23))
        self.importFileData.setObjectName("importFileData")
        self.clearData = QtWidgets.QPushButton(self)
        self.clearData.setGeometry(QtCore.QRect(110, 60, 75, 23))
        self.clearData.setObjectName("clearData")
        self.tableWidget = QtWidgets.QTableWidget(self)
        self.tableWidget.setGeometry(QtCore.QRect(50, 110, 1700, 1000))
        self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(18)
        self.tableWidget.setRowCount(0)
        self.tableWidget.verticalHeader().setVisible(False)  
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(17, item)
        self.importFileData.clicked.connect(lambda:self.importFile())
        self.clearData.clicked.connect(lambda:self.clear())

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "热管产品管理表"))
        self.importFileData.setText(_translate("Form", "导入"))
        self.clearData.setText(_translate("Form", "清空"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "产品名称"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "产品代号"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "截面形状"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "厚度"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "应用方式"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "弯曲情况"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "孔数"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Form", "20℃单孔最大传热能力"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Form", "20℃临界热流密度"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("Form", "20℃工况充装时热管线性密度"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("Form", "截面总面积"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("Form", "槽道面积"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("Form", "蒸气腔面积"))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("Form", "允许最大回退面积"))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("Form", "最大回退百分比"))
        item = self.tableWidget.horizontalHeaderItem(16)
        item.setText(_translate("Form", "充装下限"))
        item = self.tableWidget.horizontalHeaderItem(17)
        item.setText(_translate("Form", "充装上限"))
    
    def LoadData(self):
        self.productlist=ProductSelect.GetProductInfo()
        self.tableWidget.setRowCount(len(self.productlist))
        for row_number, row_data in enumerate(self.productlist):
            self.tableWidget.setItem(row_number, 0, QtWidgets.QTableWidgetItem(str(row_data["id"])))
            self.tableWidget.setItem(row_number, 1, QtWidgets.QTableWidgetItem(str(row_data["name"])))
            self.tableWidget.setItem(row_number, 2, QtWidgets.QTableWidgetItem(str(row_data["code"])))
            self.tableWidget.setItem(row_number, 3, QtWidgets.QTableWidgetItem(str(row_data["ishape"])))
            self.tableWidget.setItem(row_number, 4, QtWidgets.QTableWidgetItem(str(row_data["thickness"])))
            self.tableWidget.setItem(row_number, 5, QtWidgets.QTableWidgetItem(str(row_data["apptyle"])))
            self.tableWidget.setItem(row_number, 6, QtWidgets.QTableWidgetItem(str(row_data["wanqu"])))
            self.tableWidget.setItem(row_number, 7, QtWidgets.QTableWidgetItem(str(row_data["kongnum"])))
            self.tableWidget.setItem(row_number, 8, QtWidgets.QTableWidgetItem(str(row_data["prtkong20"])))
            self.tableWidget.setItem(row_number, 9, QtWidgets.QTableWidgetItem(str(row_data["midulinjie20"])))
            self.tableWidget.setItem(row_number, 10, QtWidgets.QTableWidgetItem(str(row_data["miduchongzhuang20"])))
            self.tableWidget.setItem(row_number, 11, QtWidgets.QTableWidgetItem(str(row_data["a"])))
            self.tableWidget.setItem(row_number, 12, QtWidgets.QTableWidgetItem(str(row_data["caoa"])))
            self.tableWidget.setItem(row_number, 13, QtWidgets.QTableWidgetItem(str(row_data["chongqiqianga"])))
            self.tableWidget.setItem(row_number, 14, QtWidgets.QTableWidgetItem(str(row_data["allowmaxa"])))
            self.tableWidget.setItem(row_number, 15, QtWidgets.QTableWidgetItem(str(row_data["allowmaxp"])))
            self.tableWidget.setItem(row_number, 16, QtWidgets.QTableWidgetItem(str(row_data["chongzhuangdn"])))
            self.tableWidget.setItem(row_number, 17, QtWidgets.QTableWidgetItem(str(row_data["chongzhuangup"])))
    
    def clear(self):
        ProductSelect.ClearTable("Product")
        self.LoadData()
        pass

    def importFile(self):
        
        data=[]
        fileName_choose, filetype = QtWidgets.QFileDialog.getOpenFileName(self,  
                                    "选取文件",  
                                    os.getcwd(), # 起始路径 
                                    "All Files (*);;Text Files (*.xlsx)")   # 设置文件扩展名过滤,用双分号间隔

        if fileName_choose == "":
            return 
        if "Product.xlsx"  in fileName_choose:
            self.clear()
        else:
            return 
        #打开文件，获取excel文件的workbook（工作簿）对象
        excel = xlrd.open_workbook(fileName_choose,encoding_override="utf-8")
        #获取sheet对象
        sheet = excel.sheets()[0]
        for each_row in range(sheet.nrows):#循环打印每一行
            if each_row==0:
                continue
            item={}
            item["id"]=int(float(sheet.cell(each_row,0).value))
            item["name"]=str(sheet.cell(each_row,1).value)
            item["code"]=sheet.cell(each_row,2).value
            item["ishape"]=sheet.cell(each_row,3).value
            item["thickness"]=float(sheet.cell(each_row,4).value)
            item["apptyle"]=str(sheet.cell(each_row,5).value)
            item["wanqu"]=str(sheet.cell(each_row,6).value)
            item["kongnum"]=str(sheet.cell(each_row,7).value)
            item["prtkong20"]=float(sheet.cell(each_row,8).value)
            item["midulinjie20"]=float(sheet.cell(each_row,9).value)
            item["miduchongzhuang20"]=float(sheet.cell(each_row,10).value)
            item["a"]=float(sheet.cell(each_row,11).value)
            item["caoa"]=float(sheet.cell(each_row,12).value)
            item["chongqiqianga"]=float(sheet.cell(each_row,13).value)
            item["allowmaxa"]=float(sheet.cell(each_row,14).value)
            item["allowmaxp"]=float(sheet.cell(each_row,15).value)
            item["chongzhuangdn"]=float(sheet.cell(each_row,16).value)
            item["chongzhuangup"]=float(sheet.cell(each_row,17).value)
            data.append(item)
        ProductSelect.InsertIntoProduct("Product",data)
        self.LoadData()

        


