# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\HotPile\UI\Ui_ProductMgr\Ui_ProductMgr.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget,QDialog
from Tools import ProductSelect


class Ui_ProductMgr(QWidget):
    def __init__(self, parent = None):
        super(QWidget, self).__init__(parent)
        self.setupUi()
        self.LoadData()

    def setupUi(self):
        self.setObjectName("Form")
        self.resize(1800, 1000)
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(890, 20, 191, 31))
        self.label.setStyleSheet("font: 75 16pt \"Agency FB\";")
        self.label.setObjectName("label")
        self.importFileData = QtWidgets.QPushButton(self)
        self.importFileData.setGeometry(QtCore.QRect(20, 60, 75, 23))
        self.importFileData.setObjectName("importFileData")
        self.clearData = QtWidgets.QPushButton(self)
        self.clearData.setGeometry(QtCore.QRect(110, 60, 75, 23))
        self.clearData.setObjectName("clearData")
        self.tableWidget = QtWidgets.QTableWidget(self)
        self.tableWidget.setGeometry(QtCore.QRect(50, 110, 1800, 1000))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.verticalHeader().setVisible(False)  
        self.tableWidget.horizontalHeader().setVisible(False)  


        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "热管产品管理表"))
        self.importFileData.setText(_translate("Form", "导入"))
        self.clearData.setText(_translate("Form", "清空"))
    
    def LoadData(self):
        self.productlist=ProductSelect.GetDensityInfo()
        print(type(self.productlist))
        pass

    def FillTable(self):
        #18lie
        pass
