# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\PYTHON\HotPile\About.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import gl 


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(246*gl.w, 166*gl.h)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30*gl.w, 30*gl.h, 54*gl.w, 12*gl.h))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30*gl.w, 60*gl.h, 54*gl.w, 12*gl.h))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30*gl.w, 90*gl.h, 54*gl.w, 12*gl.h))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(90*gl.w, 30*gl.h, 54*gl.w, 12*gl.h))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(90*gl.w, 60*gl.h, 111*gl.w, 16*gl.h))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(100*gl.w, 90*gl.h, 54*gl.w, 12*gl.h))
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "关于软件"))
        self.label.setText(_translate("Dialog", "软件版本："))
        self.label_2.setText(_translate("Dialog", "产品名称："))
        self.label_3.setText(_translate("Dialog", "版权所有："))
        self.label_4.setText(_translate("Dialog", "V1.0"))
        self.label_5.setText(_translate("Dialog", "热控产品选型软件"))
        self.label_6.setText(_translate("Dialog", "XXXXXX"))
