# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\HotPile\UI\Logo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget,QDialog
from res import picres_rc
import gl 


class LOGO(QWidget):
    def __init__(self, parent = None):
        super(QWidget, self).__init__(parent)
        self.setupUi()

    def setupUi(self):
        self.setObjectName("Form")
        self.resize(1800*gl.w, 1000*gl.h)
        # self.palette = QtGui.QPalette()
        # pix =QtGui.QPixmap(":/SingleRe/LOGO_Big.png")
        # pix = pix.scaled(self.width(),self.height())
        # self.palette.setBrush(QtGui.QPalette.Background,QtGui.QBrush(pix))
        # self.setPalette(self.palette)
        self.ReRanpic = QtWidgets.QLabel(self)
        self.ReRanpic.setGeometry(QtCore.QRect(700*gl.w, 0*gl.h, 1800*gl.w, 1000*gl.h))
        self.ReRanpic.setText("")
        self.ReRanpic.setPixmap(QtGui.QPixmap(":/SingleRe/LOGO_Big.png"))
        self.ReRanpic.setObjectName("label")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "Form"))


        # palette = QtGui.QPalette()
        # pix = QtGui.QPixmap("background.jpg”)
        # pix = pix.scaled(self.width(),self.height())
        # palette.setBrush(QtGui.QPalette.Background,QtGui.QBrush(pix))
        # self.setPalette(palette)


