# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\PYTHON\HotPile\dist\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class YeSaiTable(QtWidgets.QTableWidget):
    def setupUi(self, Table):
        Table.setObjectName("Form")
        # self.setGeometry(QtCore.QRect(0, 550, 1200, 480))
        self.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.verticalHeader().setVisible(False) 
        self.horizontalHeader().setVisible(False)
        self.setObjectName("tableWidget")

        self.retranslateUi(Table)
        QtCore.QMetaObject.connectSlotsByName(Table)

    def retranslateUi(self, Table):
        _translate = QtCore.QCoreApplication.translate
        Table.setWindowTitle(_translate("Table", "Table"))

    
    def  setTableInfo(self,Rowlist,collist):
        self.setColumnCount(len(collist)+2)
        self.setRowCount(len(Rowlist)+2)
        # self.setSpan(0,0,1,len(collist)+1)
        Item1 = QtWidgets.QTableWidgetItem('充装温度')
        Item1.setTextAlignment(QtCore.Qt.AlignCenter)
        self.setItem(0, 1, Item1)
        self.setSpan(0, 1, 1, len(collist)+1)
        Item2 = QtWidgets.QTableWidgetItem('工\n作\n温\n度')
        Item2.setTextAlignment(QtCore.Qt.AlignCenter)
        self.setItem(1, 0, Item2)
        self.setSpan(1, 0, len(Rowlist)+1, 1)
        for i in range(len(collist)+2):
            if i==0:
                self.setColumnWidth(i, 30)
            else:
                self.setColumnWidth(i, 50)
        self.setRowHeight(0,30) 
        self.setRowHeight(1,30) 
        for m in range(len(Rowlist)):
            self.setItem(m+2, 1, QtWidgets.QTableWidgetItem(str(Rowlist[m])+"℃"))
        for n in range(len(collist)):
            self.setItem(1, n+2, QtWidgets.QTableWidgetItem(str(collist[n])+"℃"))


        
