# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\PYTHON\HotPile\UI\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class YeSaiTable(QtWidgets.QTabWidget):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1119, 884)
        self.setGeometry(QtCore.QRect(0, 550, 1200, 480))
        # self.tableWidget = QtWidgets.QTableWidget(Form)
        # self.tableWidget.setGeometry(QtCore.QRect(0, 520, 256, 192))
        # self.tableWidget.setObjectName("tableWidget")
        # self.tableWidget.setColumnCount(3)
        # self.tableWidget.setRowCount(4)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setVerticalHeaderItem(0, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setVerticalHeaderItem(1, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setVerticalHeaderItem(2, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setVerticalHeaderItem(3, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setHorizontalHeaderItem(0, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setHorizontalHeaderItem(1, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setHorizontalHeaderItem(2, item)
        # self.label = QtWidgets.QLabel(Form)
        # self.label.setGeometry(QtCore.QRect(350, 520, 181, 151))
        # self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        # item = self.tableWidget.verticalHeaderItem(0)
        # item.setText(_translate("Form", "新建行"))
        # item = self.tableWidget.verticalHeaderItem(1)
        # item.setText(_translate("Form", "新建行"))
        # item = self.tableWidget.verticalHeaderItem(2)
        # item.setText(_translate("Form", "新建行"))
        # item = self.tableWidget.verticalHeaderItem(3)
        # item.setText(_translate("Form", "新建行"))
        # item = self.tableWidget.horizontalHeaderItem(0)
        # item.setText(_translate("Form", "新建列1"))
        # item = self.tableWidget.horizontalHeaderItem(1)
        # item.setText(_translate("Form", "新建列2"))
        # item = self.tableWidget.horizontalHeaderItem(2)
        # item.setText(_translate("Form", "新建列3"))
        # self.label.setText(_translate("Form", "TextLabel"))
