# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\PYTHON\HotPile\dist\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class YeSaiTable(QtWidgets.QTableWidget):
    def setupUi(self, Table):
        Table.setObjectName("Form")
        self.setGeometry(QtCore.QRect(0, 550, 1200, 480))
        self.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        # self.verticalHeader().setVisible(False) 
        self.setObjectName("tableWidget")
        # self.setColumnCount(7)
        # self.setRowCount(7)
        # item = QtWidgets.QTableWidgetItem()
        # self.setVerticalHeaderItem(0, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.setVerticalHeaderItem(1, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.setVerticalHeaderItem(2, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.setVerticalHeaderItem(3, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.setVerticalHeaderItem(4, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.setVerticalHeaderItem(5, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.setVerticalHeaderItem(6, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.setHorizontalHeaderItem(0, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.setHorizontalHeaderItem(1, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.setHorizontalHeaderItem(2, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.setHorizontalHeaderItem(3, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.setHorizontalHeaderItem(4, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.setHorizontalHeaderItem(5, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.setHorizontalHeaderItem(6, item)

        self.retranslateUi(Table)
        QtCore.QMetaObject.connectSlotsByName(Table)

    def retranslateUi(self, Table):
        _translate = QtCore.QCoreApplication.translate
        Table.setWindowTitle(_translate("Table", "Table"))
        # item = self.verticalHeaderItem(0)
        # item.setText(_translate("Table", "新建行"))
        # item = self.verticalHeaderItem(1)
        # item.setText(_translate("Table", "新建行"))
        # item = self.verticalHeaderItem(2)
        # item.setText(_translate("Table", "新建行"))
        # item = self.verticalHeaderItem(3)
        # item.setText(_translate("Table", "新建行"))
        # item = self.verticalHeaderItem(4)
        # item.setText(_translate("Table", "新建行"))
        # item = self.verticalHeaderItem(5)
        # item.setText(_translate("Table", "新建行"))
        # item = self.verticalHeaderItem(6)
        # item.setText(_translate("Table", "新建行"))
        # item = self.horizontalHeaderItem(0)
        # item.setText(_translate("Table", "新建列"))
        # item = self.horizontalHeaderItem(1)
        # item.setText(_translate("Table", "新建列"))
        # item = self.horizontalHeaderItem(2)
        # item.setText(_translate("Table", "新建列"))
        # item = self.horizontalHeaderItem(3)
        # item.setText(_translate("Table", "新建列"))
        # item = self.horizontalHeaderItem(4)
        # item.setText(_translate("Table", "新建列"))
        # item = self.horizontalHeaderItem(5)
        # item.setText(_translate("Table", "新建列"))
        # item = self.horizontalHeaderItem(6)
        # item.setText(_translate("Table", "新建列"))
    
    def  setTableInfo(self,Rowlist,collist):
        self.setColumnCount(len(collist))
        self.setRowCount(len(Rowlist))
        for i in range(len(Rowlist)):
            item = QtWidgets.QTableWidgetItem()
            self.setVerticalHeaderItem(i, item)

        for j in range(len(collist)):
            item = QtWidgets.QTableWidgetItem()
            self.setHorizontalHeaderItem(j, item)
        
        for m in range(len(Rowlist)):
            item = self.verticalHeaderItem(m)
            item.setText(str(Rowlist[m])+"℃")
        
        for n in range(len(collist)):
            item = self.horizontalHeaderItem(n)
            item.setText(str(collist[n])+"℃")

        
