# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\PYTHON\HotPile\UI\ReGuanSelect.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal
import gl

class Ui_ReGuanSelect(object):
    # 自定义信号
    mySignal = pyqtSignal(str,int)
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(447*gl.w, 893*gl.h)
        self.oData={}
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(21*gl.w, 40*gl.h, 60*gl.w, 16*gl.h))
        self.label.setObjectName("label")
        self.reliumidu = QtWidgets.QLineEdit(Form)
        self.reliumidu.setGeometry(QtCore.QRect(87*gl.w, 40*gl.h, 150*gl.w, 20*gl.h))
        self.reliumidu.setObjectName("reliumidu")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(244*gl.w, 40*gl.h, 36*gl.w, 16*gl.h))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(21*gl.w, 80*gl.h, 60*gl.w, 16*gl.h))
        self.label_4.setObjectName("label_4")
        self.type = QtWidgets.QComboBox(Form)
        self.type.setGeometry(QtCore.QRect(87*gl.w, 80*gl.h, 150*gl.w, 20*gl.h))
        self.type.setObjectName("type")
        self.type.addItem("")
        self.type.addItem("")
        self.type.addItem("")
        self.rongcha = QtWidgets.QLineEdit(Form)
        self.rongcha.setGeometry(QtCore.QRect(87*gl.w, 120*gl.h, 150*gl.w, 20*gl.h))
        self.rongcha.setObjectName("rongcha")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(21*gl.w, 120*gl.h, 60*gl.w, 16*gl.h))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(244*gl.w, 120*gl.h, 16*gl.w, 16*gl.h))
        self.label_5.setObjectName("label_5")
        self.weight = QtWidgets.QLineEdit(Form)
        self.weight.setGeometry(QtCore.QRect(87*gl.w, 160*gl.h, 150*gl.w, 20*gl.h))
        self.weight.setText("")
        self.weight.setObjectName("weight")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(244*gl.w, 160*gl.h, 16*gl.w, 16*gl.h))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(21*gl.w, 160*gl.h, 36*gl.w, 16*gl.h))
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(244*gl.w, 200*gl.h, 16*gl.w, 16*gl.h))
        self.label_8.setObjectName("label_8")
        self.hightemp = QtWidgets.QLineEdit(Form)
        self.hightemp.setGeometry(QtCore.QRect(87*gl.w, 200*gl.h, 150*gl.w, 20*gl.h))
        self.hightemp.setText("")
        self.hightemp.setObjectName("hightemp")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(21*gl.w, 200*gl.h, 60*gl.w, 16*gl.h))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(244*gl.w, 240*gl.h, 16*gl.w, 16*gl.h))
        self.label_10.setObjectName("label_10")
        self.lowtemp = QtWidgets.QLineEdit(Form)
        self.lowtemp.setGeometry(QtCore.QRect(87*gl.w, 240*gl.h, 150*gl.w, 20*gl.h))
        self.lowtemp.setText("")
        self.lowtemp.setObjectName("lowtemp")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(21*gl.w, 240*gl.h, 60*gl.w, 16*gl.h))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(244*gl.w, 280*gl.h, 16*gl.w, 16*gl.h))
        self.label_12.setObjectName("label_12")
        self.edingtemp = QtWidgets.QLineEdit(Form)
        self.edingtemp.setGeometry(QtCore.QRect(87*gl.w, 280*gl.h, 150*gl.w, 20*gl.h))
        self.edingtemp.setText("")
        self.edingtemp.setObjectName("edingtemp")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(21*gl.w, 280*gl.h, 60*gl.w, 16*gl.h))
        self.label_13.setObjectName("label_13")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(80*gl.w, 680*gl.h, 75*gl.w, 23*gl.h))
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(20*gl.w, 400*gl.h, 385*gl.w, 150*gl.h))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        self.tableWidget.resizeRowsToContents()
        # self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.tableWidget.verticalHeader().setVisible(False)  
        self.tableWidget.horizontalHeader().setVisible(False)  
        self.tableWidget.setColumnWidth(0, 40*gl.w);  
        self.tableWidget.setColumnWidth(1, 60*gl.w); 
        self.tableWidget.setColumnWidth(2, 70*gl.w); 
        self.tableWidget.setColumnWidth(3, 70*gl.w); 
        self.tableWidget.setColumnWidth(4, 70*gl.w); 
        self.tableWidget.setColumnWidth(5, 70*gl.w); 
        # self.tableWidget.setColumnWidth(5, 80); 
        # self.tableWidget.setColumnWidth(6, 80); 
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(24*gl.w, 560*gl.h, 60*gl.w, 16*gl.h))
        self.label_18.setObjectName("label_18")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(24*gl.w, 600*gl.h, 120*gl.w, 16*gl.h))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(24*gl.w, 640*gl.h, 120*gl.w, 16*gl.h))
        self.label_22.setObjectName("label_22")
        self.wanqunum = QtWidgets.QLineEdit(Form)
        self.wanqunum.setGeometry(QtCore.QRect(90*gl.w, 560*gl.h, 41*gl.w, 21*gl.h))
        self.wanqunum.setText("")
        self.wanqunum.setObjectName("wanqunum")
        self.totalgonglv_high = QtWidgets.QLabel(Form)
        self.totalgonglv_high.setGeometry(QtCore.QRect(150*gl.w, 600*gl.h, 41*gl.w, 20*gl.h))
        self.totalgonglv_high.setObjectName("totalgonglv_high")

        self.totalgonglv_low = QtWidgets.QLabel(Form)
        self.totalgonglv_low.setGeometry(QtCore.QRect(150*gl.w, 640*gl.h, 41*gl.w, 20*gl.h))
        self.totalgonglv_low.setObjectName("totalgonglv_low")


        self.chongzhuangtemp = QtWidgets.QLineEdit(Form)
        self.chongzhuangtemp.setGeometry(QtCore.QRect(86*gl.w, 320*gl.h, 150*gl.w, 20*gl.h))
        self.chongzhuangtemp.setText("")
        self.chongzhuangtemp.setObjectName("chongzhuangtemp")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(243*gl.w, 320*gl.h, 16*gl.w, 16*gl.h))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(20*gl.w, 320*gl.h, 60*gl.w, 16*gl.h))
        self.label_15.setObjectName("label_15")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(200*gl.w, 600*gl.h, 41*gl.w, 20*gl.h))
        self.label_20.setObjectName("label_20")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(200*gl.w, 640*gl.h, 41*gl.w, 20*gl.h))
        self.label_23.setObjectName("label_23")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(20*gl.w, 360*gl.h, 60*gl.w, 16*gl.h))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(244*gl.w, 360*gl.h, 16*gl.w, 16*gl.h))
        self.label_17.setObjectName("label_17")
        self.thickness = QtWidgets.QLineEdit(Form)
        self.thickness.setGeometry(QtCore.QRect(86*gl.w, 360*gl.h, 150*gl.w, 20*gl.h))
        self.thickness.setText("")
        self.thickness.setObjectName("thickness")
        # self.wanqunum.textChanged.connect(lambda:self.totalgonglv_high.setText(str(self.CalTotalgonglv(1))))
        self.wanqunum.textChanged.connect(self.ReCalGonglv)
        self.pushButton.clicked.connect(lambda:self.sendshanxuaninfo())
        self.reliumidu.textChanged.connect(lambda:self.textchange())
        # self.type.textChanged.connect(lambda:self.textchange())
        self.rongcha.textChanged.connect(lambda:self.textchange())
        self.weight.textChanged.connect(lambda:self.textchange())
        self.hightemp.textChanged.connect(lambda:self.textchange())
        self.lowtemp.textChanged.connect(lambda:self.textchange())
        self.edingtemp.textChanged.connect(lambda:self.textchange())
        self.chongzhuangtemp.textChanged.connect(lambda:self.textchange())
        self.wanqunum.textChanged.connect(lambda:self.textchange())
        self.thickness.textChanged.connect(lambda:self.textchange())
        #表格内容变化
        # self.tableWidget.itemChanged.connect(lambda:self.totalgonglv_high.setText(str(self.CalTotalgonglv(1))))
        self.tableWidget.itemChanged.connect(self.ReCalGonglv)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "热流密度："))
        self.label_2.setText(_translate("Form", "W/cm^2"))
        self.label_4.setText(_translate("Form", "应用方式："))
        self.type.setItemText(0, _translate("Form", "预埋"))
        self.type.setItemText(1, _translate("Form", "外贴"))
        self.type.setItemText(2, _translate("Form", "预埋、外贴"))
        self.label_3.setText(_translate("Form", "液塞容差："))
        self.label_5.setText(_translate("Form", "mm"))
        self.label_6.setText(_translate("Form", "g"))
        self.label_7.setText(_translate("Form", "重量："))
        self.label_8.setText(_translate("Form", "℃"))
        self.label_9.setText(_translate("Form", "高温工作："))
        self.label_10.setText(_translate("Form", "℃"))
        self.label_11.setText(_translate("Form", "低温工作："))
        self.label_12.setText(_translate("Form", "℃"))
        self.label_13.setText(_translate("Form", "额定工作："))
        self.pushButton.setText(_translate("Form", "筛选"))
        self.label_18.setText(_translate("Form", "弯曲个数："))
        self.totalgonglv_high.setText(_translate("Form", "0"))
        self.totalgonglv_low.setText(_translate("Form", "0"))
        self.label_14.setText(_translate("Form", "℃"))
        self.label_15.setText(_translate("Form", "充装温度："))
        self.label_20.setText(_translate("Form", "Wm"))
        self.label_16.setText(_translate("Form", "厚度："))
        self.label_17.setText(_translate("Form", "mm"))
        self.label_21.setText(_translate("Form", "高温工况需求总功率："))
        self.label_22.setText(_translate("Form", "低温工况需求总功率："))
        self.label_23.setText(_translate("Form", "Wm"))
        self.reliumidu.setText(_translate("Form", "1.2"))
        self.type.setCurrentText(_translate("Form", "外贴"))
        self.rongcha.setText(_translate("Form", "10"))
        self.weight.setText(_translate("Form", "12"))
        self.hightemp.setText(_translate("Form", "40"))
        self.lowtemp.setText(_translate("Form", "10"))
        self.edingtemp.setText(_translate("Form", "20"))
        self.chongzhuangtemp.setText(_translate("Form", "25"))
        self.wanqunum.setText(_translate("Form", "0"))
        self.thickness.setText(_translate("thickness", "10"))
        self.FillTableData([{
            "reyuan":"热源1",
            "gonglv_high":"50",
            "gonglv_low":"50",
            "juli":"1"
        }])  
    def sendshanxuaninfo(self):
        self.TabdataToodata()
        self.mySignal.emit(str(self.oData),1)
    
        
    
# 列表内添加按钮
    def buttonForRow(self,id):
        widget=QtWidgets.QWidget()

        # 增加
        addBtn = QtWidgets.QPushButton('+')
        addBtn.setStyleSheet(''' text-align : center;
                                  background-color : DarkSeaGreen;
                                  height : 30px;
                                  border-style: outset;
                                  font : 13px; ''')

        addBtn.clicked.connect(lambda: self.addRow())

        # 删除
        deleteBtn = QtWidgets.QPushButton('-')
        deleteBtn.setStyleSheet(''' text-align : center;
                                    background-color : LightCoral;
                                    height : 30px;
                                    border-style: outset;
                                    font : 13px; ''')
        deleteBtn.clicked.connect(lambda: self.deleteRow(id))

        hLayout = QtWidgets.QHBoxLayout()
        # hLayout.addWidget(updateBtn)
        hLayout.addWidget(addBtn)
        hLayout.addWidget(deleteBtn)
        hLayout.setContentsMargins(5,2,5,2)
        widget.setLayout(hLayout)
        return widget
    
    def FillTableData(self,tabledata):
        irow=len(tabledata)
        self.tableWidget.setRowCount(irow+1)
        titleitem=QtWidgets.QTableWidgetItem("序号")
        titleitem.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 0, titleitem)
        titleitem=QtWidgets.QTableWidgetItem("热源")
        titleitem.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 1, titleitem)
        titleitem=QtWidgets.QLabel()
        titleitem.setWordWrap(True)
        titleitem.setText("高温工况需求功率(W)")
        titleitem.setAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setCellWidget(0,2,titleitem)
        titleitem=QtWidgets.QLabel()
        titleitem.setWordWrap(True)
        titleitem.setText("低温工况需求功率(W)")
        titleitem.setAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setCellWidget(0,3,titleitem)
        titleitem=QtWidgets.QLabel()
        titleitem.setWordWrap(True)
        titleitem.setText("传热距离\n(mm)")
        titleitem.setAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setCellWidget(0,4,titleitem)
        titleitem=QtWidgets.QTableWidgetItem("操作")
        titleitem.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 5, titleitem)
        
        for row_number, row_data in enumerate(tabledata):
            # self.tableWidget.setItem(row_number, 0, QtWidgets.QTableWidgetItem(str(row_number+1)))
            self.tableWidget.setItem(row_number+1, 1, QtWidgets.QTableWidgetItem(str(row_data["reyuan"])))
            self.tableWidget.setItem(row_number+1, 2, QtWidgets.QTableWidgetItem(str(row_data["gonglv_high"])))
            self.tableWidget.setItem(row_number+1, 3, QtWidgets.QTableWidgetItem(str(row_data["gonglv_low"])))
            self.tableWidget.setItem(row_number+1, 4, QtWidgets.QTableWidgetItem(str(row_data["juli"])))
            self.tableWidget.setCellWidget(row_number+1, 5, self.buttonForRow(row_number))
            item0 = QtWidgets.QTableWidgetItem(str(row_number+1))
            item0.setFlags( QtCore.Qt.ItemIsEnabled)
            self.tableWidget.setItem(row_number+1, 0, item0)

    def addRow(self):
        self.TabdataToodata()
        item={}
        item["reyuan"]="热源"+str(len(self.oData["tabledata"])+1)
        item["gonglv_high"]=0
        item["gonglv_low"]=0
        item["juli"]=0
        self.oData["tabledata"].append(item)
        self.FillTableData(self.oData["tabledata"])
        #发送消息 当前热源个数
        dic={}
        dic["renrannum"]=len(self.oData["tabledata"])
        self.mySignal.emit(str(dic),2)
    
    def deleteRow(self,id):
        dic={}
        if len(self.oData["tabledata"])<2:
            #发送消息 当前热源个数
            dic["renrannum"]=len(self.oData["tabledata"])
            self.mySignal.emit(str(dic),2)
            return
        else:
            self.TabdataToodata()
            del self.oData["tabledata"][id]
            self.FillTableData(self.oData["tabledata"])
            #发送消息 当前热源个数
            dic["renrannum"]=len(self.oData["tabledata"])
            self.mySignal.emit(str(dic),2)
    
    #监听页面数据变化
    def textchange(self):
        self.oData["reliumidu"]=self.reliumidu.text()
        self.oData["type"]=self.type.currentText()
        self.oData["rongcha"]=self.rongcha.text()
        self.oData["weight"]=self.weight.text()
        self.oData["hightemp"]=self.hightemp.text()
        self.oData["lowtemp"]=self.lowtemp.text()
        self.oData["edingtemp"]=self.edingtemp.text()
        self.oData["chongzhuangtemp"]=self.chongzhuangtemp.text()
        self.oData["wanqunum"]=self.wanqunum.text()
        self.oData["thickness"]=self.thickness.text()
        self.totalgonglv_high.setText(str(self.CalTotalgonglv(1)))
        self.totalgonglv_low.setText(str(self.CalTotalgonglv(2)))


    #将界面中表格当前数值复制给self.oData["tabledata"]
    def TabdataToodata(self):
        data=[]
        for i in range(self.tableWidget.rowCount()):
            if i==0:
                continue
            item={}
            item["reyuan"]=self.tableWidget.item(i, 1).text()
            item["gonglv_high"]=float(self.tableWidget.item(i, 2).text())
            item["gonglv_low"]=float(self.tableWidget.item(i, 3).text())
            item["juli"]=float(self.tableWidget.item(i, 4).text())
            data.append(item)
        self.oData["tabledata"]=data
    
    #计算总功率
    #itype 1 表示计算高温  2 表示计算低温
    def CalTotalgonglv(self,itype):
        if len(self.wanqunum.text())==0 or self.tableWidget.rowCount()==0:
            self.oData["wanqunum"]=0
        else:
            self.oData["wanqunum"]=float(self.wanqunum.text())
        reyuangonglv=0
        icoulumn=2 if itype==1 else 3
        for  i in range(self.tableWidget.rowCount()):
            if isinstance(self.tableWidget.item(i, icoulumn), QtWidgets.QTableWidgetItem) and isinstance(self.tableWidget.item(i, 4), QtWidgets.QTableWidgetItem):
                tempvaule=float(self.tableWidget.item(i, icoulumn).text())*float(self.tableWidget.item(i, 4).text())
                reyuangonglv=reyuangonglv+tempvaule
            else:
                pass
        if self.oData["wanqunum"]==0:
            return reyuangonglv*1e-3
        else:
            return reyuangonglv*(1+self.oData["wanqunum"]*0.1)*1e-3
    
    def ReCalGonglv(self):
        self.totalgonglv_high.setText(str(self.CalTotalgonglv(1)))
        self.totalgonglv_low.setText(str(self.CalTotalgonglv(2)))