# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\HotPile\UI\Ui_CanshuChuxuan\CanshuChuxuan.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget,QDialog
import gl 



class Ui_CanshuChuxuan(QWidget):
    def __init__(self, parent = None):
        super(QWidget, self).__init__(parent)
        self.setupUi()

    def setupUi(self):
        self.setObjectName("Form")
        self.resize(1800*gl.w, 1000*gl.h)
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(90*gl.w, 20*gl.h, 54*gl.w, 12*gl.h))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(20*gl.w, 60*gl.h, 100*gl.w, 23*gl.h))
        self.label_2.setObjectName("label_2")
        self.Zhengfa_DaoTong = QtWidgets.QLineEdit(self)
        self.Zhengfa_DaoTong.setGeometry(QtCore.QRect(140*gl.w, 60*gl.h, 75*gl.w, 23*gl.h))
        self.Zhengfa_DaoTong.setObjectName("Zhengfa_DaoTong")
        self.label_3 = QtWidgets.QLabel(self)
        self.label_3.setGeometry(QtCore.QRect(220*gl.w, 60*gl.h, 75*gl.w, 23*gl.h))
        self.label_3.setObjectName("label_3")
        self.ChuqiStart_DaoTong = QtWidgets.QLineEdit(self)
        self.ChuqiStart_DaoTong.setGeometry(QtCore.QRect(140*gl.w, 110*gl.h, 75*gl.w, 23*gl.h))
        self.ChuqiStart_DaoTong.setObjectName("ChuqiStart_DaoTong")
        self.label_4 = QtWidgets.QLabel(self)
        self.label_4.setGeometry(QtCore.QRect(20*gl.w, 110*gl.h, 100*gl.w, 23*gl.h))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self)
        self.label_5.setGeometry(QtCore.QRect(220*gl.w, 110*gl.h, 75*gl.w, 23*gl.h))
        self.label_5.setObjectName("label_5")
        self.ChuqiJiange_DaoTong = QtWidgets.QLineEdit(self)
        self.ChuqiJiange_DaoTong.setGeometry(QtCore.QRect(140*gl.w, 160*gl.h, 75*gl.w, 23*gl.h))
        self.ChuqiJiange_DaoTong.setObjectName("ChuqiJiange_DaoTong")
        self.label_6 = QtWidgets.QLabel(self)
        self.label_6.setGeometry(QtCore.QRect(20*gl.w, 160*gl.h, 100*gl.w, 23*gl.h))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self)
        self.label_7.setGeometry(QtCore.QRect(220*gl.w, 160*gl.h, 75*gl.w, 23*gl.h))
        self.label_7.setObjectName("label_7")
        self.ChuqiEnd_DaoTong = QtWidgets.QLineEdit(self)
        self.ChuqiEnd_DaoTong.setGeometry(QtCore.QRect(140*gl.w, 210*gl.h, 75*gl.w, 23*gl.h))
        self.ChuqiEnd_DaoTong.setObjectName("ChuqiEnd_DaoTong")
        self.label_8 = QtWidgets.QLabel(self)
        self.label_8.setGeometry(QtCore.QRect(20*gl.w, 210*gl.h, 100*gl.w, 23*gl.h))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self)
        self.label_9.setGeometry(QtCore.QRect(220*gl.w, 210*gl.h, 75*gl.w, 23*gl.h))
        self.label_9.setObjectName("label_9")
        self.Zhengfa_ZuSei = QtWidgets.QLineEdit(self)
        self.Zhengfa_ZuSei.setGeometry(QtCore.QRect(140*gl.w, 310*gl.h, 75*gl.w, 23*gl.h))
        self.Zhengfa_ZuSei.setObjectName("Zhengfa_ZuSei")
        self.label_10 = QtWidgets.QLabel(self)
        self.label_10.setGeometry(QtCore.QRect(220*gl.w, 420*gl.h, 75*gl.w, 23*gl.h))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self)
        self.label_11.setGeometry(QtCore.QRect(20*gl.w, 420*gl.h, 100*gl.w, 23*gl.h))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self)
        self.label_12.setGeometry(QtCore.QRect(20*gl.w, 520*gl.h, 100*gl.w, 23*gl.h))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self)
        self.label_13.setGeometry(QtCore.QRect(220*gl.w, 520*gl.h, 75*gl.w, 23*gl.h))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self)
        self.label_14.setGeometry(QtCore.QRect(20*gl.w, 470*gl.h, 100*gl.w, 23*gl.h))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self)
        self.label_15.setGeometry(QtCore.QRect(220*gl.w, 470*gl.h, 75*gl.w, 23*gl.h))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self)
        self.label_16.setGeometry(QtCore.QRect(90*gl.w, 270*gl.h, 54*gl.w, 12*gl.h))
        self.label_16.setObjectName("label_16")
        self.ChuqiStart_ZuSei = QtWidgets.QLineEdit(self)
        self.ChuqiStart_ZuSei.setGeometry(QtCore.QRect(140*gl.w, 420*gl.h, 75*gl.w, 23*gl.h))
        self.ChuqiStart_ZuSei.setObjectName("ChuqiStart_ZuSei")
        self.ChuqiEnd_ZuSei = QtWidgets.QLineEdit(self)
        self.ChuqiEnd_ZuSei.setGeometry(QtCore.QRect(140*gl.w, 520*gl.h, 75*gl.w, 23*gl.h))
        self.ChuqiEnd_ZuSei.setObjectName("ChuqiEnd_ZuSei")
        self.label_17 = QtWidgets.QLabel(self)
        self.label_17.setGeometry(QtCore.QRect(20*gl.w, 310*gl.h, 100*gl.w, 23*gl.h))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self)
        self.label_18.setGeometry(QtCore.QRect(220*gl.w, 310*gl.h, 75*gl.w, 23*gl.h))
        self.label_18.setObjectName("label_18")
        self.ChuqiJiange_ZuSei = QtWidgets.QLineEdit(self)
        self.ChuqiJiange_ZuSei.setGeometry(QtCore.QRect(140*gl.w, 470*gl.h, 75*gl.w, 23*gl.h))
        self.ChuqiJiange_ZuSei.setObjectName("ChuqiJiange_ZuSei")
        self.LengNing_ZuSei = QtWidgets.QLineEdit(self)
        self.LengNing_ZuSei.setGeometry(QtCore.QRect(140*gl.w, 360*gl.h, 75*gl.w, 23*gl.h))
        self.LengNing_ZuSei.setText("")
        self.LengNing_ZuSei.setObjectName("LengNing_ZuSei")
        self.label_19 = QtWidgets.QLabel(self)
        self.label_19.setGeometry(QtCore.QRect(20*gl.w, 360*gl.h, 100*gl.w, 23*gl.h))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self)
        self.label_20.setGeometry(QtCore.QRect(220*gl.w, 360*gl.h, 75*gl.w, 23*gl.h))
        self.label_20.setObjectName("label_20")
        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setGeometry(QtCore.QRect(80*gl.w, 570*gl.h, 75*gl.w, 23*gl.h))
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtWidgets.QTableWidget(self)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.hide()
        # self.tableWidget.setColumnCount(0)
        # self.tableWidget.setRowCount(0)

        self.retranslateUi(self)
        self.InitData()
        self.BindingEvents()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "全导通"))
        self.label_2.setText(_translate("Form", "蒸发段温度"))
        self.label_3.setText(_translate("Form", "℃"))
        self.label_4.setText(_translate("Form", "储气室起始温度"))
        self.label_5.setText(_translate("Form", "℃"))
        self.label_6.setText(_translate("Form", "储气室间隔温度"))
        self.label_7.setText(_translate("Form", "℃"))
        self.label_8.setText(_translate("Form", "储气室终止温度"))
        self.label_9.setText(_translate("Form", "℃"))
        self.label_10.setText(_translate("Form", "℃"))
        self.label_11.setText(_translate("Form", "储气室起始温度"))
        self.label_12.setText(_translate("Form", "储气室终止温度"))
        self.label_13.setText(_translate("Form", "℃"))
        self.label_14.setText(_translate("Form", "储气室间隔温度"))
        self.label_15.setText(_translate("Form", "℃"))
        self.label_16.setText(_translate("Form", "全阻断"))
        self.label_17.setText(_translate("Form", "蒸发段温度"))
        self.label_18.setText(_translate("Form", "℃"))
        self.label_19.setText(_translate("Form", "冷凝阻塞段温度"))
        self.label_20.setText(_translate("Form", "℃"))
        self.pushButton.setText(_translate("Form", "计算"))
    
    def InitData(self):
        self.data={
            "Zhengfa_DaoTong":20,
            "ChuqiStart_DaoTong":20,
            "ChuqiJiange_DaoTong":5,
            "ChuqiEnd_DaoTong":40,
            "Zhengfa_ZuSei":20,
            "ChuqiStart_ZuSei":20,
            "ChuqiJiange_ZuSei":5,
            "ChuqiEnd_ZuSei":40,
            "LengNing_ZuSei":20,
        }
        self.Zhengfa_DaoTong.setText(str(self.data["Zhengfa_DaoTong"]))
        self.ChuqiStart_DaoTong.setText(str(self.data["ChuqiStart_DaoTong"]))
        self.ChuqiJiange_DaoTong.setText(str(self.data["ChuqiJiange_DaoTong"]))
        self.ChuqiEnd_DaoTong.setText(str(self.data["ChuqiEnd_DaoTong"]))
        self.Zhengfa_ZuSei.setText(str(self.data["Zhengfa_ZuSei"]))
        self.ChuqiStart_ZuSei.setText(str(self.data["ChuqiStart_ZuSei"]))
        self.ChuqiJiange_ZuSei.setText(str(self.data["ChuqiJiange_ZuSei"]))
        self.ChuqiEnd_ZuSei.setText(str(self.data["ChuqiEnd_ZuSei"]))
        self.LengNing_ZuSei.setText(str(self.data["LengNing_ZuSei"]))
    
    #绑定事件
    def BindingEvents(self):
        self.pushButton.clicked.connect(self.cal)

    
    def cal(self):
        self.data["Zhengfa_DaoTong"]=int(float(self.Zhengfa_DaoTong.text()))
        self.data["ChuqiStart_DaoTong"]=int(float(self.ChuqiStart_DaoTong.text()))
        self.data["ChuqiJiange_DaoTong"]=int(float(self.ChuqiJiange_DaoTong.text()))
        self.data["ChuqiEnd_DaoTong"]=int(float(self.ChuqiEnd_DaoTong.text()))
        self.data["Zhengfa_ZuSei"]=int(float(self.Zhengfa_ZuSei.text()))
        self.data["ChuqiStart_ZuSei"]=int(float(self.ChuqiStart_ZuSei.text()))
        self.data["ChuqiJiange_ZuSei"]=int(float(self.ChuqiJiange_ZuSei.text()))
        self.data["ChuqiEnd_ZuSei"]=int(float(self.ChuqiEnd_ZuSei.text()))
        self.data["LengNing_ZuSei"]=int(float(self.LengNing_ZuSei.text()))
        self.tableWidget.show()
        self.showTable()
        

    #根据输入参数生成数据
    def makedata(self):
        temp_DaoTong=self.data["ChuqiStart_DaoTong"]
        temp_ZuSei=self.data["ChuqiStart_ZuSei"]
        res=[[temp_DaoTong],[temp_ZuSei]]
        while (temp_DaoTong<self.data["ChuqiEnd_DaoTong"]):
            temp_DaoTong=temp_DaoTong+self.data["ChuqiJiange_DaoTong"]
            res[0].append(temp_DaoTong) 
            if temp_DaoTong+self.data["ChuqiJiange_DaoTong"]>=self.data["ChuqiEnd_DaoTong"]:
                res[0].append(self.data["ChuqiEnd_DaoTong"]) 
                break
            else:
                pass
        while (temp_ZuSei<self.data["ChuqiEnd_ZuSei"]):
            temp_ZuSei=temp_ZuSei+self.data["ChuqiJiange_ZuSei"]
            res[1].append(temp_ZuSei) 
            if temp_ZuSei+self.data["ChuqiJiange_ZuSei"]>=self.data["ChuqiEnd_ZuSei"]:
                res[1].append(self.data["ChuqiEnd_ZuSei"]) 
                break
            else:
                pass
        return res
    
    #表格
    def showTable(self):
        self.tableWidget.verticalHeader().setVisible(False) 
        self.tableWidget.horizontalHeader().setVisible(False)
        tableData=self.makedata()
        self.tableWidget.setColumnCount(len(tableData[0])+3)
        self.tableWidget.setRowCount(len(tableData[1])+3)
        totalw=0
        totalh=0
        w=40
        h=35
        for index2 in range(len(tableData[0])+3):
            w=0
            if index2==0 or index2==1:
                w=40
            else:
                w=60
            totalw=totalw+w
            self.tableWidget.setColumnWidth(index2, w*gl.w);
        for index3 in range(len(tableData[1])+3):
            totalh=totalh+h
            self.tableWidget.setRowHeight(index3,h*gl.h)
        self.tableWidget.setGeometry(QtCore.QRect(300*gl.w, 75*gl.h, (totalw+2)*gl.w, (totalh+2)*gl.h))

        #合并单元格内容设置
        Item1 = QtWidgets.QTableWidgetItem('Vr/Vc')
        Item1.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 0, Item1)
        self.tableWidget.setSpan(0, 0, 2, 2)
        Item2 = QtWidgets.QTableWidgetItem('导通Vr温度')
        Item2.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 2, Item2)
        self.tableWidget.setSpan(0, 2, 1,len(tableData[0])+1)
        Item3 = QtWidgets.QTableWidgetItem('阻断Vr温度')
        Item3.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(2, 0, Item3)
        self.tableWidget.setSpan(2, 0,len(tableData[1])+1,1)
        self.tableWidget.setItem(1, 2, QtWidgets.QTableWidgetItem("℃"))
        self.tableWidget.setItem(2, 1, QtWidgets.QTableWidgetItem("℃"))
        self.tableWidget.setItem(2, 2, QtWidgets.QTableWidgetItem("K"))
        for index in range(len(tableData[0])):
            self.tableWidget.setItem(1, index+3, QtWidgets.QTableWidgetItem(str(tableData[0][index])))
            self.tableWidget.setItem(2, index+3, QtWidgets.QTableWidgetItem(""))
        for index1 in range(len(tableData[1])):
            self.tableWidget.setItem(index1+3, 1, QtWidgets.QTableWidgetItem(str(tableData[1][index1])))
            self.tableWidget.setItem(index1+3, 2, QtWidgets.QTableWidgetItem(""))
        self.setStyleSheet()

    #设置表格样式
    def setStyleSheet(self):
        #亮灰色
        tableData=self.makedata()
        color_gray=QtGui.QColor(211, 211, 211, 160)
        self.tableWidget.item(0,0).setBackground(color_gray)
        self.tableWidget.item(0,2).setBackground(color_gray)
        self.tableWidget.item(2,0).setBackground(color_gray)
        self.tableWidget.item(2,1).setBackground(color_gray)
        self.tableWidget.item(2,2).setBackground(color_gray)
        self.tableWidget.item(1,2).setBackground(color_gray)
        for index in range(len(tableData[0])):
            self.tableWidget.item(1, index+3).setBackground(color_gray)
            self.tableWidget.item(2, index+3).setBackground(color_gray)
        for index1 in range(len(tableData[1])):
            self.tableWidget.item(index1+3, 1).setBackground(color_gray)
            self.tableWidget.item(index1+3, 2).setBackground(color_gray)
