# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'd:\PYTHON\HotPile\UI\Ui_XiangxiPinggu\XiangxiPinggu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget,QDialog
from Tools import ProductSelect
import gl 


class Ui_XiangxiPinggu(QWidget):
    def __init__(self, parent = None):
        super(QWidget, self).__init__(parent)
        self.setupUi()

    def setupUi(self):
        self.setObjectName("self")
        self.resize(1800*gl.w, 1000*gl.h)
        self.DaoTong_PingGu = QtWidgets.QPushButton(self)
        self.DaoTong_PingGu.setGeometry(QtCore.QRect(60*gl.w, 90*gl.h, 100*gl.w, 30*gl.h))
        self.DaoTong_PingGu.setObjectName("DaoTong_PingGu")
        self.ZhengFa_PingGu = QtWidgets.QPushButton(self)
        self.ZhengFa_PingGu.setGeometry(QtCore.QRect(60*gl.w, 150*gl.h, 100*gl.w, 30*gl.h))
        self.ZhengFa_PingGu.setObjectName("ZhengFa_PingGu")
        self.label_3 = QtWidgets.QLabel(self)
        self.label_3.setGeometry(QtCore.QRect(360*gl.w, 90*gl.h, 70*gl.w, 25*gl.h))
        self.label_3.setObjectName("label_3")
        self.ChuanreGongzhi = QtWidgets.QComboBox(self)
        self.ChuanreGongzhi.setGeometry(QtCore.QRect(460*gl.w, 90*gl.h, 70*gl.w, 25*gl.h))
        self.ChuanreGongzhi.setObjectName("ChuanreGongzhi")
        self.ChuanreGongzhi.addItem("")
        self.ChuanreGongzhi.addItem("")
        self.ChuanreGongzhi.addItem("")
        self.label_4 = QtWidgets.QLabel(self)
        self.label_4.setGeometry(QtCore.QRect(600*gl.w, 90*gl.h, 70*gl.w, 25*gl.h))
        self.label_4.setObjectName("label_4")
        self.KongzhiQiti = QtWidgets.QComboBox(self)
        self.KongzhiQiti.setGeometry(QtCore.QRect(700*gl.w, 90*gl.h, 70*gl.w, 25*gl.h))
        self.KongzhiQiti.setObjectName("KongzhiQiti")
        self.KongzhiQiti.addItem("")
        self.KongzhiQiti.addItem("")
        self.KongzhiQiti.addItem("")
        self.KongzhiQiti.addItem("")
        self.GuanXin = QtWidgets.QComboBox(self)
        self.GuanXin.setGeometry(QtCore.QRect(920*gl.w, 90*gl.h, 70*gl.w, 25*gl.h))
        self.GuanXin.setObjectName("GuanXin")
        self.label_5 = QtWidgets.QLabel(self)
        self.label_5.setGeometry(QtCore.QRect(820*gl.w, 90*gl.h, 70*gl.w, 25*gl.h))
        self.label_5.setObjectName("label_5")
        self.tableWidget = QtWidgets.QTableWidget(self)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.hide()
        self.retranslateUi(self)
        self.InitData()
        self.BindingEvents()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "Form"))
        self.DaoTong_PingGu.setText(_translate("self", "导通比例评估"))
        self.ZhengFa_PingGu.setText(_translate("self", "蒸发段温度评估"))
        self.label_3.setText(_translate("self", "传热工质："))
        self.ChuanreGongzhi.setItemText(0, _translate("self", "NH3"))
        self.ChuanreGongzhi.setItemText(1, _translate("self", "乙烷"))
        self.ChuanreGongzhi.setItemText(2, _translate("self", "丙烯"))
        self.label_4.setText(_translate("self", "控制气体："))
        self.KongzhiQiti.setItemText(0, _translate("self", "N2"))
        self.KongzhiQiti.setItemText(1, _translate("self", "Ne"))
        self.KongzhiQiti.setItemText(2, _translate("self", "H2"))
        self.KongzhiQiti.setItemText(3, _translate("self", "He"))
        self.label_5.setText(_translate("self", "管型："))
    
    def InitData(self):
        Productlist=ProductSelect.GetProductInfo()
        for i in range(len(Productlist)):
            self.GuanXin.addItem("")
            self.GuanXin.setItemText(i, Productlist[i]["code"])
        self.data={
            "title_DaoTong":['储气室温度(℃)','冷凝阻塞段温度(℃)','蒸发段温度(℃)','物质的量(mol)','储气室容积(ml)','Vr/Vc','导通比例(%)'],
            "title_ZhengFa":['储气室温度(℃)','冷凝阻塞段温度(℃)','导通比例(%)','物质的量(mol)','储气室容积(ml)','Vr/Vc','蒸发段温度(℃)'],
        }
 
    
    #绑定事件
    def BindingEvents(self):
        self.DaoTong_PingGu.clicked.connect(self.ClickDaoTongPingGu)
        self.ZhengFa_PingGu.clicked.connect(self.ZhengFaPingGu)
    
    def ClickDaoTongPingGu(self):
        self.DaoTong_PingGu.setStyleSheet(
            "color:rgb(0,0,255)"
        )
        self.ZhengFa_PingGu.setStyleSheet(
            "color:rgb(0,0,0)"
        )
        if self.tableWidget.isHidden():
            self.tableWidget.show()
        self.showTable(1)
      

    def ZhengFaPingGu(self):
        self.ZhengFa_PingGu.setStyleSheet(
            "color:rgb(0,0,255)"
        )
        self.DaoTong_PingGu.setStyleSheet(
            "color:rgb(0,0,0)"
        )
        if self.tableWidget.isHidden():
            self.tableWidget.show()
        self.showTable(2)
 
    
    def showTable(self,itype):
        self.tableWidget.verticalHeader().setVisible(False) 
        self.tableWidget.horizontalHeader().setVisible(False)
        tableData=self.makedata(itype)
        self.tableWidget.setColumnCount(len(tableData["title"]))
        self.tableWidget.setRowCount(len(tableData["data"])+1)
        totalw=0
        totalh=0
        w=120
        h=35
        for index in range(len(tableData["title"])):
            self.tableWidget.setColumnWidth(index, w*gl.w);
            totalw=totalw+w
        for index2 in range(len(tableData["data"])):
            self.tableWidget.setRowHeight(index2, h*gl.h);
            totalh=totalh+h
        self.tableWidget.setGeometry(QtCore.QRect(360*gl.w, 150*gl.h, (totalw+5)*gl.w,(totalh+40)*gl.h))
        for index1 in range(len(tableData["title"])):
            self.tableWidget.setItem(0, index1, QtWidgets.QTableWidgetItem(str(tableData["title"][index1])))
        for index3 in range(len(tableData["data"])):
            for index4 in range(len(tableData["data"][index3])):
                #临时代码
                if len(str(tableData["data"][index3][index4]))>0:
                    self.tableWidget.setItem(index3+1, index4, QtWidgets.QTableWidgetItem(str(tableData["data"][index3][index4])+"假数据"))
                else:
                    self.tableWidget.setItem(index3+1, index4, QtWidgets.QTableWidgetItem(""))
        self.setStyleSheet()


    #根据输入参数生成数据
    def makedata(self,itype):
        res={}
        res["title"]=self.data["title_DaoTong"] if itype==1 else self.data["title_ZhengFa"]
        res["data"]=[[21,25,65,84,62,54,12],[56,32,45,77,854,21,65],['','','','','','','']]
        return res
    

    #设置表格样式
    def setStyleSheet(self):
        #亮灰色
        tableData=self.makedata(1)
        color_gray=QtGui.QColor(211, 211, 211, 160)
        for index in range(len(tableData["data"])):
            self.tableWidget.item(index, len(tableData["title"])-1).setBackground(color_gray)
        self.tableWidget.item(index+1, len(tableData["title"])-1).setBackground(color_gray)
