# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Python\CalPile\Index.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget
from Ui_first import Ui_Form
from Ui_second import Ui_2
# from Ui_second import Ui_First
# from Ui_third import Ui_First

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1536, 897)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 1501, 871))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.first = First()
        self.second = Second()
        self.gridLayout.addWidget(self.second, 1, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.iflag=2
        self.pushButton.clicked.connect(lambda :self.load1(1))
        self.pushButton_2.clicked.connect(lambda :self.load1(2))
        self.pushButton_3.clicked.connect(lambda :self.load1(3))
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "单桩基础或垂直于外力作用平面的单排桩基础"))
        self.pushButton_2.setText(_translate("MainWindow", "位于（或平行于）外力作用平面的单排（或多排）底桩承台基础"))
        self.pushButton_3.setText(_translate("MainWindow", "位于（或平行于）外力作用平面的单排（或多排）高桩承台基础"))
    
    def load1(self,index):
        if index==self.iflag:
            return
        if index==1:
            self.second.close()
            self.first = First()
            self.gridLayout.addWidget(self.first, 1, 0, 1, 3)
            self.iflag=1
        elif index==2:
            self.first.close()
            self.second = Second()
            self.gridLayout.addWidget(self.second, 1, 0, 1, 3)
            self.iflag=2
        elif index==3:
            pass
        else:
            pass

class First(QWidget, Ui_Form):
    def __init__(self):
        super(First,self).__init__()
        # 子窗口初始化时实现子窗口布局
        self.setupUi(self)
 
        # 设置子窗体最小尺寸
        self.setMinimumWidth(30)
        self.setMinimumHeight(30)

class Second(QWidget, Ui_2):
    def __init__(self):
        super(Second,self).__init__()
        # 子窗口初始化时实现子窗口布局
        self.setupUi(self)
 
        # 设置子窗体最小尺寸
        self.setMinimumWidth(30)
        self.setMinimumHeight(30)

if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())